apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-test
  template:
    metadata:
      labels:
        app: node-test
    spec:
      containers:
      - name: app
        image: ghcr.io/jupiter778/node_test_jenkins:latest
        ports:
        - containerPort: 3000
